---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgAqG5cuqcGIRWBACu09DJ2GdiGIxRzIhFOy+96qcBMdKGodiH3BIs48XuZiR/ZFH/dX6V6RLk+N0Ci+QtZaI7QkeKjMWuEDWaXG2Li3/ObQvs5U7YND/bX09V3pTLCJBDvPtPvl132WAL0FPdwu3dLJV2TmkH3p2JzyRvGGz1bkBMjQmU7UhXEY67qG0qVpyVngDkAmcBNvoym2l/3WLKr8ln4mJoRqcXHl1Yh9StVWib9YMEUOKrS8jc2YEdEU5j0zacv0V4tDMfKxWu4Cr5KCqElizq/rOboT9T0gUzjoEn8DWTQjSn7+H1GIy0bFaZJl6dR1b1sbOansmz/x8TYsi6Iupbu2bgmPTecwUMRIqKJo6ixVmvph79tYhSWVihxEpItMGl6+ahYBFKq28vY6dXK4+yaiRm47g3FmL2vbpS4ao2L/sOmP3OwNhIqocSLyTFFuIe2o9lldOKJXwqyBUx46/OIKltQ56OJgsrBlEH1A6rMkYHrHt9nmnSKx81ys3RKoX8ZzVGd56Tg9izGzkuiX7TwIp9oWHc/2jCxQ6CyQUm85GT+vp44cn7F/vFTjAOka+YN7b7ooCNjcfVXEDqEdJR6ANwXJ0jlcUT1GgYzCocs11EMQH5Dcc5lUhNcpn3iOt3WoiMwdWH45zrb3ZgpICUJsjmldQ5Io+Rbc3BL3c/FaN4pAW1P+so7UpvNc6ySpAEF23E5B/UkDlAnUrzvTCg==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgBp2inpqXPRyH+bDmlcG+szk7DjWonik8lN9Tn6AjM8cXsDmusKbA1K+PWrCGsamFByIXPJssEOLX6tZUDljdgvCT7LPdOsOB66yxYc6k1dp0125ekwm4Nqd2q/j/fxd7ZnSQMTj0WKHuwDG++Ql/EIuoSJOBuAojRkk+CCBrZXQaKALRfegBCM0VQNfbT3jocHEYYqwgx/zEwi1S+1LndnH/dfYDV+aICWLObBPgqVbUGX2OCwfoAxpjaoREfQ59RU+Zir8+0ED6y9OMxgScIc+zB1TTbdldUdw5ASzEWNoUkpInKhYq/oGUlIou9nM6tGAmN9OGOyZcoKnNw3xcabfgxPcakyICxhaw+qqblBv2aj55rIxUaHr8Q5NVYUDl0ufQ0rQpA+s+PwEuOjfl4sEgQg4rbn4G+vMUiHYWSJ8uQOWstPdWtN8o8nIIkVS0vRPwwnNJUez+yEpEe8aG397LuvoGZyg2jeRJYPsb4fALiuve8WLS4L6aflHXy9xLKEJK7cCn4TRe31s1mQkpzxyUw41OmRwKrzk0oYIuFrUrjAKg4dd5GTpC2CnqIsi6kNb89YVF+LikClpM4wgXmqXlAO1POEgpowWUZrIFb9iy+KMTw+UERnSFaAIxdaoZQdbghCHHSHpddJJLGGN+edocb5jV5801Grp6Et6tWr3jseBqnWL8L63BctvCFjo65+W8FelFolaB34LMvmxqU54dTpTNdxN2pWkhVrjqJBmENhheSlQsl1
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring
