---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCXlsH3BOyhVXzRRS5QOnnK/N+oaWXgHT2JDyi0NC7Z6Leu/kzmrDUkNpDseIHVCZMhdBgHDr/zNOg59U1LydJ1lRjtiuVt8uVht7lCzY3ZRvHabRFs1rn7L2oS49rIxtZ01eMoNQ/2JoPTAC5i+ePSewfwtreBEXjg/napDNB2P4mkjH03O/njF1hFhSNxXBwCVda8MuYztEB/0sSKwW/sxi0E0XJQmNmjt1NC9mDwxu0XVoAkNXz5SNkvSX9joGh43zxJS47tQu8aGJ3+QZApyqqZOiR0M1cE1YFqaVF0KPo0dfh1BQatb0tkEPPJx6gW6MUFdIOykMtwY1afK6TyBZqvcrVRrweyLn4J5H8Jy/hIC939XrxsWoZW0yqrjhHg5yWhp+ZvgX720sI14XDlfOHu4XjwPZhh4qDlj0RhE1MhrmnDwDqe4kl+iU3iDVMV9x2Nf3QMrp93+2FIp/XO3gJaz3UNZ1MHQECkvPu9JCs5mjdxfzwcN04gWVjybILxgwqPrl6y8EsTEseq/ZPsxy5i8bdrlqJuqDOnkVrYK1dLfYGdMVXnK5wVPI+WUcKDy5d9EngnvyeCu8s5ZBoUy8Aapr1P4KNMtad3Hq41KeZaAcmLH6Eq8iF4Kxrpus6/N7xP3DMiCZx5Xv27td2mxUbg6QfSItNZ7pKTGGfHMKOY4X01SGwkrNO5JZhHZM5aKK7jT/AKqIR+HBVcK2C+
    admin-user: AgBpBKNkp/xlo7+LK3mi1m4FuSU2nvFMd/6iz1AvKEmQa1FH4nc2Jkdo+oJkFzAbed2RKfNC76sDPlZeKXjjLxKAQS0h3xZLQx4tk+xCTFjrWKy1puUxex1NNDCYdwgNyWGs9FF/F8+K6jdSiVpACRaa4I7JNeMjimNqCGhmt8rurYP4nhHmfeeluGMepJdXx14L7G9R24dFfLXuq2VbN4ZzAAJyxbn7N+xB4Tq9ss5n5Gew8710w2wF94qkhS4+Ytwv5wD+fSGtODr1akbBFwvq4TLpAHRUx8MvqSW/fzDT9Y6kpFoJrzq5vvgKzVdURrz1FXX/HFuhFrNUcAniKYI5yLV3j4fjXriNVdfjKY6PdMsJfmRxZyuLkHpN5O7T3fSsgGmr1qE2iQf9J7DMV4EK7M2OHCxzrOMQ6vAKFAJRZo0hH08y5XmZFtDTuq8ZVVq79wcEIjmqQb6iUpleit4775MM00QKnnazyVGOg7FI0FzPXr4xpmCBX429pBl6+te96dmN0bfpU3kPLSrsboIgoqrsAliXLX3mk+CcekXkpUIA5ZCb4Ctv82wjoFxmiNpmwFsRhFZZVSQUGrkQ8FhJFM3yKSTQxzd5jlU8AtUEXgrkOCaQqP8PmybI795D2R8f7vMeQLA4tED/YMMVVfKa/B8Fzm+6mJAOb9ls5SlzdAX5lleejlDHKhu7Ujta58/rr6OM/A==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
