apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: "0.12.0"
    helm:
      values: |
        immich:
          persistence:
            library:
              existingClaim: immich-library
        controllers:
          main:
            containers:
              main:
                env:
                  DB_HOSTNAME: immich-postgres
                  DB_USERNAME: immich
                  DB_PASSWORD: immich
                  DB_DATABASE_NAME: immich
        server:
          ingress:
            main:
              enabled: false
        valkey:
          enabled: true
          controllers:
            main:
              containers:
                main:
                  image:
                    repository: docker.io/valkey/valkey
                    tag: 9.1-alpine
          persistence:
            data:
              enabled: true
              type: persistentVolumeClaim
              size: 1Gi
              storageClass: nfs
              accessMode: ReadWriteOnce
        machine-learning:
          persistence:
            cache:
              enabled: true
              type: persistentVolumeClaim
              size: 10Gi
              storageClass: nfs
              accessMode: ReadWriteMany
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
